version: '3'
services:
  frontend:
    build: ./parigolo-frontend
    ports:
      - '80:80'
  backend:
    build: ./parigolo-backend
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://parigolo:ParigoloPassword@db:3306/parigolodb
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=ParigoloRootPassword
      - MYSQL_DATABASE=parigolodb
      - MYSQL_USER=parigolo
      - MYSQL_PASSWORD=ParigoloPassword
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: