# Use an official Node.js runtime as the base image
FROM node:14
# Set the working directory in the container to /app
WORKDIR /app
# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
# Install the application dependencies
RUN npm install
# Copy the rest of the application code to the working directory
COPY . .
# Set environment variable for polling
ENV CHOKIDAR_USEPOLLING=true
# Copy the env.sh script and make it executable
COPY env_dev.sh .
RUN chmod +x env_dev.sh
# Start the application
CMD ["/bin/sh", "-c", "./env_dev.sh && npm start"]